Modified checkbox styles for custom radio buttons
feathery-org/feathery-react pull request #313
Opened 2022-02-10 21:27 UTC by drewj

2022-02-10 21:45 UTC, bo-dun-1 requested changes

2022-02-10 21:45 UTC, bo-dun-1 commented on src/elements/fields/RadioButtonGroupField.jsx
> +            css={{ ...composeCheckboxStyle(styles, true, 'radio') }}
css={composeCheckboxStyle()}?

2022-02-10 21:45 UTC, bo-dun-1 commented on src/elements/fields/CheckboxGroupField.jsx
> -              alignItems: 'flex-start',
doens't this center the text when we should be fixing to top?

2022-02-10 21:45 UTC, bo-dun-1 commented on src/elements/fields/RadioButtonGroupField.jsx
> +  applyStyles.addTargets(['checkboxGroup']);
can we call this radioGroup

2022-02-10 21:47 UTC, drewj commented on src/elements/fields/RadioButtonGroupField.jsx
> +            css={{ ...composeCheckboxStyle(styles, true, 'radio') }}
Whoops

2022-02-12 03:10 UTC, bo-dun-1 approved these changes

2022-02-12 03:10 UTC, bo-dun-1 commented on src/elements/fields/RadioButtonGroupField.jsx
> +    applyCheckboxStyles(element, applyStyles);
Can we call this something more generic? A little confusing when it looks like youre appliyng checkbox styles to a radio group

2022-02-15 00:05 UTC, merged